### ISSUE TITLE
Update references to "First Steps" Link

### ISSUE THREAD

**Issue by dlothian** [roedoejet/wordweaver-docs#2]
At the bottom of the https://docs.wordweaver.ca/docs/intro page, there is a link that leads to a Page Not Found.
Highlighted in green in the attatched picture.

![Screen Shot 2020-07-15 at 3 30 32 PM](https://user-images.githubusercontent.com/22920735/87598285-50c73e00-c6b0-11ea-9b2f-fd8c541e6460.png)

**Comment by dlothian** [comment]
Second instance, bottom of page https://docs.wordweaver.ca/docs/installation/

![Screen Shot 2020-07-15 at 3 38 12 PM](https://user-images.githubusercontent.com/22920735/87600570-38a3ee80-c6b1-11ea-8bd7-fb5642556be9.png)

**Comment by dlothian** [comment]
So the issue is, and there might be some more, the incorrect link is https://docs.wordweaver.ca/docs/firststeps.md and the correct link, which sometimes exists, is https://docs.wordweaver.ca/docs/firststeps

**Comment by roedoejet** [comment]
Cool! This was super helpful, I fixed the links here: 6737f300 and ran a link checker. Might be nice to move this step into the ci

Getting links from: http://localhost:8000/
├───OK─── http://localhost:8000/img/android-chrome-512x512.png
├───OK─── http://localhost:8000/docs/
├───OK─── http://localhost:8000/blog
├───OK─── https://github.com/nrc-cnrc/wordweaver
├───OK─── http://localhost:8000/docs/features
├───OK─── http://localhost:8000/docs/firststeps
├───OK─── https://github.com/roedoejet/wordweaver-docs
Finished! 31 links found. 24 excluded. 0 broken.

Getting links from: http://localhost:8000/docs/
├───OK─── http://localhost:8000/docs/intro
├───OK─── http://localhost:8000/docs/installation
├───OK─── http://localhost:8000/docs/ww-custom-intro
├───OK─── http://localhost:8000/docs/wwui-custom-intro
├───OK─── http://localhost:8000/docs/gramble-intro
├───OK─── http://localhost:8000/docs/ww-ui-style
├───OK─── http://localhost:8000/docs/ww-ui-validation
├───OK─── http://localhost:8000/docs/ww-i18n
├───OK─── http://localhost:8000/docs/ww-ui-types
├───OK─── https://nrc.canada.ca/en/node/1378
├───OK─── http://onkwawenna.info/
├───OK─── https://github.com/roedoejet/wordweaver-docs/edit/master/docs/ww-intro.md
Finished! 65 links found. 53 excluded. 0 broken.

Getting links from: http://localhost:8000/blog
├───OK─── http://localhost:8000/blog/welcome
├───OK─── https://github.com/roedoejet
├───OK─── https://avatars3.githubusercontent.com/u/14815080?v=4
├───OK─── http://localhost:8000/blog/tags/welcome
├───OK─── http://localhost:8000/blog/tags/wordweaver
Finished! 40 links found. 35 excluded. 0 broken.

Getting links from: http://localhost:8000/docs/features
├───OK─── https://fastapi.tiangolo.com/
├───OK─── http://nginx.org/en/
├───OK─── https://www.docker.com/
├───OK─── https://docs.docker.com/compose/
├───OK─── https://angular.io/
├───OK─── https://ngrx.io/
├───OK─── http://www.ngx-translate.com/
├───OK─── https://github.com/roedoejet/wordweaver-docs/edit/master/docs/ww-features.md
Finished! 70 links found. 62 excluded. 0 broken.

Getting links from: http://localhost:8000/docs/firststeps
├───OK─── https://github.com/roedoejet/wordweaver-docs/edit/master/docs/ww-firststeps.md
Finished! 64 links found. 63 excluded. 0 broken.

Getting links from: http://localhost:8000/docs/intro
Finished! 65 links found. 65 excluded. 0 broken.

Getting links from: http://localhost:8000/docs/installation
├───OK─── https://en.wikipedia.org/wiki/Git
├───OK─── https://en.wikipedia.org/wiki/Command-line_interface
├───OK─── https://en.wikipedia.org/wiki/Python_(programming_language)
├───OK─── https://en.wikipedia.org/wiki/Docker_(software)
├───OK─── https://en.wikipedia.org/wiki/Npm_(software)
├───OK─── https://github.com/roedoejet/wordweaver-docs/edit/master/docs/ww-installation.md
Finished! 67 links found. 61 excluded. 0 broken.

Getting links from: http://localhost:8000/docs/ww-custom-intro
├───OK─── https://www.nginx.com/resources/wiki/
├───OK─── https://iso639-3.sil.org/
├───OK─── https://stackoverflow.com/questions/19335215/what-is-a-slug
├───OK─── https://letsencrypt.org/
├───OK─── https://github.com/roedoejet/wordweaver-docs/edit/master/docs/ww-customization.md
Finished! 103 links found. 98 excluded. 0 broken.

Getting links from: http://localhost:8000/docs/wwui-custom-intro
├───OK─── https://en.wikipedia.org/wiki/ISO_639-3
├───OK─── http://localhost:8000/docs/wwui-page-about
├───OK─── https://github.com/roedoejet/wordweaver-docs/edit/master/docs/ww-ui-customization.md
Finished! 126 links found. 123 excluded. 0 broken.

Getting links from: http://localhost:8000/docs/gramble-intro
├───OK─── https://github.com/littell/gramble_ts
├───OK─── https://github.com/roedoejet/wordweaver-docs/edit/master/docs/gramble-intro.md
Finished! 80 links found. 78 excluded. 0 broken.

Getting links from: http://localhost:8000/docs/ww-ui-style
├───OK─── https://sass-lang.com/
├───OK─── https://material.io/design/color/the-color-system.html#color-usage-and-palettes
├───OK─── http://mcg.mbitson.com/
├───OK─── https://github.com/roedoejet/wordweaver-docs/edit/master/docs/ww-ui-style.md
Finished! 75 links found. 71 excluded. 0 broken.

Getting links from: http://localhost:8000/docs/ww-ui-validation
├───OK─── https://github.com/roedoejet/wordweaver-docs/edit/master/docs/ww-ui-validation.md
Finished! 57 links found. 56 excluded. 0 broken.

Getting links from: http://localhost:8000/docs/ww-i18n
├───OK─── https://en.wikipedia.org/wiki/JSON
├───OK─── https://iso639-3.sil.org/code_tables/639/data
├───OK─── https://www.codeandweb.com/babeledit
├───OK─── https://poeditor.com/
├───OK─── https://github.com/ngx-translate/core
├───OK─── https://github.com/biesbjerg/ngx-translate-extract
├───OK─── https://github.com/roedoejet/wordweaver-docs/edit/master/docs/ww-i18n.md
Finished! 80 links found. 73 excluded. 0 broken.

Getting links from: http://localhost:8000/docs/ww-ui-types
├───OK─── https://github.com/roedoejet/wordweaver-docs/edit/master/docs/types.md
Finished! 74 links found. 73 excluded. 0 broken.

Getting links from: http://localhost:8000/blog/welcome
├───OK─── https://github.com/roedoejet/wordweaver-docs/edit/master/blog/2020-05-22-welcome.md
Finished! 38 links found. 37 excluded. 0 broken.

Getting links from: http://localhost:8000/blog/tags/welcome
├───OK─── http://localhost:8000/blog/tags
Finished! 42 links found. 41 excluded. 0 broken.

Getting links from: http://localhost:8000/blog/tags/wordweaver
Finished! 42 links found. 42 excluded. 0 broken.

Getting links from: http://localhost:8000/docs/wwui-page-about
├───OK─── https://github.com/roedoejet/wordweaver-docs/edit/master/docs/ww-ui-page-about.md
Finished! 38 links found. 37 excluded. 0 broken.

Getting links from: http://localhost:8000/blog/tags
Finished! 32 links found. 32 excluded. 0 broken.

Finished! 1189 links found. 1124 excluded. 0 broken.
Elapsed time: 14 seconds
